# Generated by Django 5.1.4 on 2024-12-17 17:37

import api.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', api.models.CharFieldCustom(max_length=8)),
                ('gender', models.CharField(choices=[('0', 'Male'), ('1', 'Female')], max_length=1, validators=[django.core.validators.RegexValidator(code='invalid_gender', message='Gender must be 0 (male) or 1 (female)', regex='^[01]$')])),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Age must be at least zero'), django.core.validators.MaxValueValidator(limit_value=100, message='Age must be at the most 100')])),
            ],
        ),
        migrations.CreateModel(
            name='Petshop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('entry_date_petshop', models.DateTimeField(auto_now_add=True)),
                ('exit_date_petshop', models.DateTimeField(blank=True, null=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='api.breed')),
                ('petshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='api.petshop')),
            ],
            options={
                'unique_together': {('id', 'petshop')},
            },
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_date', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to='api.person')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to='api.pet')),
                ('petshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to='api.petshop')),
            ],
            options={
                'unique_together': {('pet', 'petshop', 'person')},
            },
        ),
    ]
