# Generated by Django 5.1.4 on 2024-12-17 17:53

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=api.models.CharFieldCustom(choices=[('0', 'Male'), ('1', 'Female')], max_length=1, validators=[django.core.validators.RegexValidator(code='invalid_gender', message='Gender must be 0 (male) or 1 (female)', regex='^[01]$')]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
