# Generated by Django 5.1.4 on 2024-12-17 19:58

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_adoption_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=api.models.CharFieldCustom(max_length=1),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(('gender', '0'), ('gender', '1'), _connector='OR'), name='chk_person_gender'),
        ),
    ]
